try
    error("system failure")
except
    print("exception handled")

print("normal routine")
